name: stac_vscode_preview_host
description: Local Flutter web renderer for stac-vscode preview panel.
publish_to: 'none'

version: 0.1.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.6.0
  stac: ^1.3.1
  web: any

flutter:
  uses-material-design: true
