name: stac
description: Stac is a Server-Driven UI (SDUI) framework for Flutter. Stac allows you to build beautiful cross-platform applications with JSON in real time.
version: 1.5.0
repository: https://github.com/StacDev/stac
homepage: https://stac.dev/

environment:
  sdk: ^3.9.2
  flutter: ">=1.17.0"

topics:
  - ui
  - widget
  - server-driven-ui
  - dynamic-widgets

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.9.0
  flutter_validators: ^1.2.0
  dio: ^5.9.0
  stac_framework: ^1.0.0
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.3
  stac_logger: ^1.1.0
  stac_core: ^1.5.0
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  json_serializable: ^6.11.3
