name: stac_logger
description: A lightweight and reusable logging utility for the Stac framework.
version: 1.1.0
homepage: https://github.com/StacDev/stac
repository: https://github.com/StacDev/stac/tree/dev/packages/stac_logger

environment:
  sdk: ^3.8.1

dependencies:
  logger: ^2.5.0

dev_dependencies:
  test: ^1.24.0
  lints: ^6.0.0
